"""empty message

Revision ID: 3ea97a0a1853
Revises: afb974586aae
Create Date: 2023-06-04 07:15:48.785274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea97a0a1853'
down_revision = 'afb974586aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recomendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('recomendation_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['destination'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recomendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('recomendation_name_key', ['name'])
        batch_op.drop_column('destination')

    # ### end Alembic commands ###
