"""empty message

Revision ID: 8bccff96062f
Revises: 3ea97a0a1853
Create Date: 2023-06-04 07:27:01.897360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bccff96062f'
down_revision = '3ea97a0a1853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination')
    )
    op.drop_table('recomendation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recomendation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('destination', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='recomendation_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recomendation_pkey'),
    sa.UniqueConstraint('destination', name='recomendation_destination_key')
    )
    op.drop_table('favoritos')
    # ### end Alembic commands ###
